# -*- coding: utf-8 -*-
"""Causal Ghosts: Retrospective Counterfactuals & Epistemic Uncertainty.ipynb

Automatically generated by Colab.

Original file is located at:
    https://colab.research.google.com/drive/1g3iHKNi4uozQozgg3jcyTLdgxZyYm7AQ?usp=sharing
"""

# =====================================================================
# CELL 1: Setup and Parameter Configurations
# =====================================================================
import numpy as np
import os
import scipy.stats as stats
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Setting global random seeds for strict reproducible assertions matching essay values
np.random.seed(42)

# Set stylistic parameters for our elegant, dark academic plotting
plt.rcParams.update({
    'figure.facecolor': '#0e0d0b',
    'axes.facecolor': '#0e0d0b',
    'text.color': '#c8bfaa',
    'axes.labelcolor': '#c8bfaa',
    'xtick.color': '#6b6358',
    'ytick.color': '#6b6358',
    'grid.color': '#1f1e1b',
    'font.family': 'serif',
    'font.serif': ['Georgia', 'Times New Roman'],
    'axes.edgecolor': '#2a2823'
})

print("Cell 1 complete: Parameters configured with seed=42.")

# =====================================================================
# CELL 2: Rung 1 vs Rung 2 Recap (Confounding & do-operator)
# =====================================================================
n_recap = 5000
w_recap = np.random.beta(2, 5, size=n_recap) 
x_recap = np.random.binomial(1, p=np.clip(0.8 - w_recap, 0.0, 1.0))
y_recap = 2.0 * x_recap + 35.0 * w_recap + np.random.normal(0, 0.1, size=n_recap)

naive_coef = y_recap[x_recap == 1].mean() - y_recap[x_recap == 0].mean()
reg_recap = LinearRegression().fit(np.column_stack((x_recap, w_recap)), y_recap)
adjusted_coef = reg_recap.coef_[0]

print(f"\n--- RUNG 1 vs RUNG 2 RECAP ---")
print(f"Naive Observational Coefficient P(Y | X) : {naive_coef:.4f}")
print(f"True Causally Adjusted Effect P(Y | do(X)): {adjusted_coef:.4f} (True: 2.0000)")

# =====================================================================
# CELL 3: Twin-Network Counterfactual Estimator
# =====================================================================
n_twin = 1000
x_twin = np.random.normal(0, 1, n_twin)
u_t = np.random.normal(0, 1, n_twin)
u_y = np.random.normal(0, 0.5, n_twin)

t_twin = 0.5 * x_twin + u_t
y_twin = 2.0 * t_twin + 1.5 * x_twin + u_y

X_reg = np.column_stack((t_twin, x_twin))
scm_model = LinearRegression().fit(X_reg, y_twin)
beta_t = scm_model.coef_[0]
beta_x = scm_model.coef_[1]
alpha_intercept = scm_model.intercept_

x_obs_0 = x_twin[0]
t_obs_0 = t_twin[0]
y_obs_0 = y_twin[0]

u_y_abducted = y_obs_0 - (beta_t * t_obs_0 + beta_x * x_obs_0 + alpha_intercept)
t_counterfactual = 1.0 - t_obs_0
y_counterfactual_pred = beta_t * t_counterfactual + beta_x * x_obs_0 + alpha_intercept + u_y_abducted
y_counterfactual_true = 2.0 * t_counterfactual + 1.5 * x_obs_0 + u_y[0]

print(f"\n--- TWIN-NETWORK INDIVIDUAL RETROSPECTIVE ---")
print(f"Factual Observation of Subject 0: X={x_obs_0:.4f}, T={t_obs_0:.4f}, Y={y_obs_0:.4f}")
print(f"Abducted Noise Variable U_Y       : {u_y_abducted:.4f} (True U_Y: {u_y[0]:.4f})")
print(f"Counterfactual Action            : Force T from {t_obs_0:.4f} to {t_counterfactual:.4f}")
print(f"Predicted Counterfactual Outcome : {y_counterfactual_pred:.4f}")
print(f"True Counterfactual Outcome      : {y_counterfactual_true:.4f}")
print(f"Absolute Prediction Error        : {abs(y_counterfactual_true - y_counterfactual_pred):.6f}")

# =====================================================================
# CELL 4: Empirical Surprise 1: ITE Heterogeneity Under Zero ATE
# =====================================================================
np.random.seed(42)
n_surprise = 5000

z_s = np.random.normal(0, 1, n_surprise)           
u_y_s = np.random.normal(0, 0.5, n_surprise)      
p_select = 1 / (1 + np.exp(-0.5 * z_s))
t_s = np.random.binomial(1, p_select)

y0_s = 3.0 * z_s + u_y_s                     
y1_s = 3.0 * z_s + 2.0 * z_s + u_y_s          
y_obs_s = t_s * y1_s + (1 - t_s) * y0_s

ate_observational = y_obs_s[t_s == 1].mean() - y_obs_s[t_s == 0].mean()
true_ate_interventional = (y1_s - y0_s).mean()            
individual_effects = y1_s - y0_s                     

percent_harmed = (individual_effects < 0).mean() * 100
percent_saved = (individual_effects > 0).mean() * 100

print(f"\n--- EMPIRICAL SURPRISE 1: HETEROGENEITY ---")
print(f"Rung 1 Observational Difference P(Y|T=1)-P(Y|T=0)  : {ate_observational:.4f}")
print(f"Rung 2 Population Causal Effect (True ATE)        : {true_ate_interventional:.4f}")
print(f"Rung 3 Individual Treatment Effect (ITE) Deviation: {individual_effects.std():.4f}")
print(f"True ITE Minimum Value                            : {individual_effects.min():.4f}")
print(f"True ITE Maximum Value                            : {individual_effects.max():.4f}")
print(f"Percentage of Population Actively Harmed by Policy : {percent_harmed:.2f}%")
print(f"Percentage of Population Actively Saved by Policy  : {percent_saved:.2f}%")

# =====================================================================
# CELL 5: Empirical Surprise 2: Non-Identifiability and Manski Bounds
# =====================================================================
np.random.seed(42)
n_bounds = 10000

u_b = np.random.uniform(0, 1, n_bounds)
v_b = np.random.uniform(0, 1, n_bounds)  # Structural noise for Y
t_b = (np.random.uniform(0, 1, n_bounds) < 0.3 + 0.4 * u_b).astype(int)
y_b = (v_b < 0.5 * t_b + 0.4 * u_b).astype(int)

# Calculating Manski's worst-case non-parametric bounds for the ATE
p_y1_t1 = y_b[t_b==1].mean()
p_y1_t0 = y_b[t_b==0].mean()
p_t1 = t_b.mean()
p_t0 = 1.0 - p_t1

manski_lb = p_y1_t1 * p_t1 + 0.0 * p_t0 - (p_y1_t0 * p_t0 + 1.0 * p_t1)
manski_ub = p_y1_t1 * p_t1 + 1.0 * p_t0 - (p_y1_t0 * p_t0 + 0.0 * p_t1)
manski_width = manski_ub - manski_lb

monotonicity_lb = 0.0
monotonicity_ub = p_y1_t1 * p_t1 + (1.0 - p_y1_t0) * p_t0
mon_width = monotonicity_ub - monotonicity_lb
improvement = (1 - (mon_width / manski_width)) * 100

# Calculate true causal effect from potential outcomes on the same subjects
y1_b = (v_b < 0.5 * 1 + 0.4 * u_b).astype(int)
y0_b = (v_b < 0.5 * 0 + 0.4 * u_b).astype(int)
true_effect = (y1_b - y0_b).mean()

print(f"\n--- EMPIRICAL SURPRISE 2: NON-IDENTIFIABILITY ---")
print(f"Without assumptions, ATE in [{manski_lb:.4f}, {manski_ub:.4f}] — width = {manski_width:.4f}")
print(f"With monotonicity, ATE in [{monotonicity_lb:.4f}, {monotonicity_ub:.4f}] — width = {mon_width:.4f}")
print(f"True Simulated Causal Effect: {true_effect:.4f} (Theoretical: 0.5000)")
print(f"The monotonicity assumption reduced uncertainty by {improvement:.2f}%")

# =====================================================================
# CELL 6: The Philosophical Moment (Plotting the Causal Ghost)
# =====================================================================
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6), facecolor='#0e0d0b')

# Plot 1: Sorted Individual Treatment Effects (ITE)
ax1.set_facecolor('#141310')
sorted_ites = np.sort(individual_effects)
ax1.plot(sorted_ites, color='#c8bfaa', linewidth=2.5, label='Individual Effect ($\tau_i$)')
ax1.axhline(0, color='#8b7355', linestyle='--', linewidth=1.5, label=f'True ATE ({true_ate_interventional:.4f})')
ax1.fill_between(range(len(sorted_ites)), sorted_ites, 0, where=(sorted_ites < 0), color='#8b7355', alpha=0.15)
ax1.fill_between(range(len(sorted_ites)), sorted_ites, 0, where=(sorted_ites > 0), color='#c8bfaa', alpha=0.1)

ax1.set_title('Individual Treatment Effects (ITE) Distribution', fontsize=13, fontstyle='italic', pad=15, color='#c8bfaa')
ax1.set_xlabel('Population Index (Sorted by Effect Size)', fontsize=11, color='#c8bfaa')
ax1.set_ylabel('Causal Treatment Effect ($Y_1 - Y_0$)', fontsize=11, color='#c8bfaa')
ax1.grid(True, color='#1f1e1b', alpha=0.5)
ax1.legend(loc='upper left', frameon=False, labelcolor='#c8bfaa')

# Plot 2: Causal Effect Bounds Comparison
ax2.set_facecolor('#141310')
bounds_labels = ['Manski Worst-Case\n(No Assumptions)', 'Monotonicity\n(Assumed No-Harm)']
lower_limits = [manski_lb, monotonicity_lb]
upper_limits = [manski_ub, monotonicity_ub]

# Draw bounds as horizontal bars
ax2.barh(bounds_labels, [upper_limits[0] - lower_limits[0], upper_limits[1] - lower_limits[1]], 
         left=lower_limits, height=0.3, color=['#8b7355', '#4a3f2f'], edgecolor='#2a2823', alpha=0.8)

# Mark the factual true causal effect
ax2.axvline(true_effect, color='#c8bfaa', linestyle='--', linewidth=2, label=f'True Causal Effect ({true_effect:.4f})')
ax2.axvline(0.0, color='#2a2823', linestyle='-', linewidth=1)

ax2.set_title('Epistemic Constraints on Causal Reasoning', fontsize=13, fontstyle='italic', pad=15, color='#c8bfaa')
ax2.set_xlabel('Causal Effect Size (ATE)', fontsize=11, color='#c8bfaa')
ax2.set_xlim([-0.5, 1.0])
ax2.grid(True, color='#1f1e1b', alpha=0.5)
ax2.legend(loc='lower right', frameon=False, labelcolor='#c8bfaa')

# Clean and show layout
plt.tight_layout()
plot_path = os.path.join(os.path.dirname(__file__), 'causal_ghosts_plot.png')
plt.savefig(plot_path, dpi=300)
plt.close()

print(f"\nAll simulations run successfully. The causal ghosts have been saved to {plot_path}.")
